### ISSUE TITLE
 The website encountered an unexpected error. Please try again later.  InvalidArgumentException: No check has been registered for access_check.permission in Drupal\Core\Access\CheckProvider->loadCheck() (line 97 of core/lib/Drupal/Core/Access/CheckProvider.php). 

### ISSUE THREAD

**Issue by alauzon** [amazeeio/drupal-example#49]
After doing the 4 steps in the README.md of this project + installing the default install in english + configure name of site password, etc I get this error:
 The website encountered an unexpected error. Please try again later.

`InvalidArgumentException: No check has been registered for access_check.permission in Drupal\Core\Access\CheckProvider->loadCheck() (line 97 of core/lib/Drupal/Core/Access/CheckProvider.php). `

**Comment by rocketeerbkw** [comment]
I encountered the same error but I can't reproduce now. In my case, I had some leftover vendor folders and local docker images from a previous install. After totally deleting everything and starting over it works as expected.
