### ISSUE TITLE
Add Redis failover

### ISSUE THREAD

**Issue by vincenzodnp** [amazeeio/drupal-example#69]
If the Redis module is enabled and the Redis endpoint is not reachable (for example during maintenance), Drupal website goes down.

It might be worth adding the Redis failover configuration as described here:
https://github.com/govCMS/govcms8lagoon/blob/develop/.docker/images/govcms8/settings/settings.php#L145-L215

**Comment by pirog** [comment]
Ran into this building a certain integration as well. Was easy enough to work around but could be useful for people who want to disable//comment out `redis` locally to minimize the container footprint. 

That said, still getting up to speed on the amazeesauce so not sure whether commenting out services is a thing people do or not.
